env:
  global:
    - PATH=$HOME/.local/bin:$PATH

language: bash
before_deploy:
  - "./build_neo_release"
deploy:
  provider: releases
  api_key:
    secure: "H2+X/5vG5jVLde1mgGaclQQ4+FcQMZmSdBOWrUhC3Mn3LswjIRWDPt9GyRLZm0uGoz9TYDKFa75IqYJfr2ECBCXYtVh8y3ha/d/6rU+kTOFfw1ejjXmCvMc3Rxn+NlMzh0bOjtqC6yi5c6YzkqBx2OfGMQvuFGzHlPq5INEDeVf4M9bgbpyoIhQSXL0JE0P56D86ydDj1WaWYccgsYA9sPcrWHvrr7+KKNSyetQc4oUpnPnsa9Mapr8Zbl4GQStGXgxuMkhpEV1FBBa8d/wwVuz2lfXRj0b2M57uPSirhyceSU+NzNuYIJ3XLCt40AjeoFpfB79OK2SMRtHc9RcciSSxZZDCM7qv1+CMGY0JTnnIkugQTYKZX4+yCdqSl7xuMdSQ9OrtRscxuAcr1R2e3tAutAsvdKx2LUzZr7FEI9EDRrhvJVDg2E9BSWJwb2s0VY9DgSrGExC9oBCDHBPnKyQhOVcHea/YddIEjFlPplTtJtApD6iOSHEXzHN0aUTnAke7kXQr0tTXCo9fSVXZz0LVjBY3ISsVuJizQuywQE1ZZujg5sfAl7R9D5Zkc6rswj5Idkf28Lu0ZkDf/pL/9GCbRV2dClFk8c9/tbf2hDHYE6bM1KjXfw7eR6Kn6MIBS6ziCUz2nBeXIAq8LFnX6ePGmruNHm1ix/S0AYXG8wE="
  file:
    - release/SpoqaHanSansNeo_all.zip
    - release/SpoqaHanSansNeo_OTF_original.zip
    - release/SpoqaHanSansNeo_OTF_subset.zip
    - release/SpoqaHanSansNeo_TTF_original.zip
    - release/SpoqaHanSansNeo_TTF_subset.zip
  skip_cleanup: true
  on:
    tags: true
after_deploy:
  - pip install --user awscli
  - "./upload_s3"
